#Создание счетов

POST http://localhost:8080/addAccount
Content-Type: application/json

{
  "username": "Denis",
  "pin": 2343,
  "amountOfAccounts": 3
}

###

#Создание счетов, если клиент не найден
POST http://localhost:8080/addAccount
Content-Type: application/json

{
  "username": "Nikita",
  "pin": 2343,
  "amountOfAccounts": 3
}

###

#Создание счетов, если неверно введен пин
POST http://localhost:8080/addAccount
Content-Type: application/json

{
  "username": "Denis",
  "pin": 1111,
  "amountOfAccounts": 3
}

###

POST http://localhost:8080/addAccount
Content-Type: application/json

{
  "username": "Denis",
  "pin": 11111,
  "amountOfAccounts": 3
}

###

POST http://localhost:8080/addAccount
Content-Type: application/json

{
  "username": "Denis",
  "pin": 111,
  "amountOfAccounts": 3
}

