#Снятие средств

POST http://localhost:8080/operation/withdraw
Content-Type: application/json

{
  "username": "Denis",
  "pin": 2343,
  "accountNumber":  1292937931691,
  "amountOfOperation": 1000
}

###

#Снятие средств, если недостаточно средств

POST http://localhost:8080/operation/withdraw
Content-Type: application/json

{
  "username": "Denis",
  "pin": 2343,
  "accountNumber":  1292937931691,
  "amountOfOperation": 10000000
}

###

#Снятие средств, если неверное имя пользователя

POST http://localhost:8080/operation/withdraw
Content-Type: application/json

{
  "username": "Sonic",
  "pin": 2343,
  "accountNumber":  1292937931691,
  "amountOfOperation": 1000
}

###

#Снятие средств, если неверный пин-код

POST http://localhost:8080/operation/withdraw
Content-Type: application/json

{
  "username": "Denis",
  "pin": 1111,
  "accountNumber":  1292937931691,
  "amountOfOperation": 1000
}

###

POST http://localhost:8080/operation/withdraw
Content-Type: application/json

{
  "username": "Denis",
  "pin": 111,
  "accountNumber":  1292937931691,
  "amountOfOperation": 1000
}

###

POST http://localhost:8080/operation/withdraw
Content-Type: application/json

{
  "username": "Denis",
  "pin": 11111,
  "accountNumber":  1292937931691,
  "amountOfOperation": 1000
}

###

#Снятие средств, если неверные номера счетов

POST http://localhost:8080/operation/withdraw
Content-Type: application/json

{
  "username": "Denis",
  "pin": 2343,
  "accountNumber":  1000000,
  "amountOfOperation": 1000
}



